### PR TITLE
Changes to support client-side load-balancing with Eureka and GRPC Java.

### PR DESCRIPTION
**Pull request by imberda**

### CODE REVIEW

**Comment by imberda** [comment]
To verify load-balancing start 2 instances of the server with the "server1" and "server2" profiles respectively. This will allow each to listen on different ports locally. The `books` response now contains the server name that served the request (ie. `server-#`). 

To verify correct load-balancing, you can start and stop the servers and watch as the requests route to one or both of the servers depending on availability. Interestingly GRPC automatically handles bad nodes and re-routes away from unavailable nodes which are still listed as addresses by the name resolver. So nodes that go down are immediately taken offline by GRPC when a request fails. 

Conversely GRPC only knows about newly active nodes when notified by the name resolver. This only happens when the name resolver is updated by an event. This depends on the cache update frequency configured for Eureka. Typically this is within 30 seconds.

**Comment by szantopeter** [comment]
Hi @imberda ,

I created a separate project for the grpc-eureka library here :

https://github.com/ExampleDriven/grpc-eureka-java

This is an open source reusable library that I published to maven central. I kept this project as a "reference implementation". The only problem is it conflicts with your change :( Your PR is quite nice, would you mind reapplying it to the new structure? I have only one comment :

I tried to limit the number of transitive dependencies that comes with grpc-eureka-java as much as possible. I noticed that you use lombok, is it essential?

Thanks

Peter

**Comment by imberda** [comment]
Sure I don't mind migrating the change to the dedicated project. Should be able to do this over the next few day...

However one thought crossed my mind regarding security. In serious (i.e. real-world) usage the `ManagedChannel` would use TLS. However I think the solution will have problems as the authority supplied is the logical service name and the connections will be made to the instance nodes. This means that the authority will be something like `MY-SERVICE` and the certificates presented will contain `node1.domain.com`. 

This issue is described at this issue: https://github.com/grpc/grpc-java/pull/2662 

There are some _suggested approaches_ in the link above. Just wanted to get your thoughts on how to approach?

**Comment by szantopeter** [comment]
hmm, interesting question, I don't know the answer, it should be tested to understand how it works. If you want I can add a docker and docker compose to the reference implementation project next week, it helps testing such cases.

**Pull request closed without merging**
